#106 | Tingting | Read a promotion BDD test
PromoSquad/promotions pull request #123
Opened 2021-11-28 02:30 UTC by Tingtingyy

2021-11-28 02:57 UTC, dizys requested changes

2021-11-28 02:57 UTC, dizys commented on features/promotions.feature
> +  And I press the "Retrieve" but
`button` is not spelled completely here.

2021-11-28 03:12 UTC, dizys approved these changes
LGTM.

2021-11-28 03:14 UTC, merged

2021-11-28 03:15 UTC, Tingtingyy commented
close #106

2021-12-05 21:43 UTC, dizys commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/555adb64-8497-4119-b8ce-3e3c764c7597?env_id=ibm:yp:us-south "nyu-devops-promotions-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/70ccc3da-a493-45e2-9db5-075c3d858058 "nyu-promotion-service-fall2103") deployed [promotions](https://github.com/PromoSquad/promotions/releases/tag/deploy-ibm-yp-us-south-yk2494-nyu.edu-prod-20211205-214310 "deploy-ibm-yp-us-south-yk2494-nyu.edu-prod-20211205-214310") to [prod](https://console.bluemix.net/apps/05bb5f7f-3579-466f-b3c0-177b78bf73e4?env_id=ibm:yp:us-south "ibm:yp:us-south:yk2494@nyu.edu:prod"), including commit 58999f70a096e37b24e95f2fc07a43f0096de8d5