Modify the requirements.txt and the README file to adding the honcho …
PromoSquad/promotions pull request #90
Opened 2021-11-15 22:11 UTC by GaryAvc

modify requirements.txt and readme

2021-11-15 22:23 UTC, dizys requested changes

2021-11-15 22:23 UTC, dizys commented on README.md
> +
![微信截图_20211115171838](https://user-images.githubusercontent.com/23469706/141862036-fd8f4f8f-9423-4d01-9adc-d4eb73de0e12.png)
This is causing disorder. Please fix this and also meaningfully title this section as well.

2021-11-15 22:23 UTC, dizys commented on README.md
> +	{
I don't see the point of adding more spaces as indent here. Do you mind changing them back?
Same as below.

2021-11-15 22:40 UTC, GaryAvc commented
Modify the README file to make sure everything shows properly :)

2021-11-15 22:51 UTC, dizys requested changes

2021-11-15 22:51 UTC, dizys commented on README.md
> +
Unfortunately, this is missing ```. So its still messing up with rest of the README file.
![微信截图_20211115171838](https://user-images.githubusercontent.com/23469706/141865069-fafc980a-4bea-467e-9783-1a028a94a756.png)

2021-11-16 01:41 UTC, dizys approved these changes

2021-11-16 01:43 UTC, dizys commented
I fixed the problem myself. Please start earlier and leave more time for code review and changes in later sprints.

2021-11-16 01:43 UTC, merged